server:
  port: 8080
spring:
  thymeleaf:
    check-template-location: true
    servlet:
      content-type: text/html
    suffix: .html
    prefix: classpath:/templates/
    cache: false
  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/cart?serverTimezone=UTC
    driver-class-name:  com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

mybatis:
  type-aliases-package: com.xsk.cart.model
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/config/mybatis-config.xml

logging:
  level:
    com.xsk.cart.mapper: debug